### Get /
GET http://localhost:8000

### Post /register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
   "username": "testemail@gmail.com",
   "password": "1234256562413"
}

### Post /login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
   "username": "testemail@gmail.com",
   "password": "1234256562413"
}